import Link from "next/link";
import { ArrowLeft, ShieldCheck, Scale, AlertOctagon } from "lucide-react";

export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen bg-main-bg py-20 relative overflow-hidden">
      {/* BACKGROUND monogram */}
      <div className="absolute right-[-100px] top-10 font-display font-black text-primary-black/[0.01] text-[30rem] md:text-[50rem] leading-none select-none pointer-events-none z-0">
        AN
      </div>

      <div className="max-w-[1440px] mx-auto px-6 md:px-12 lg:px-24 relative z-10">
        {/* Back Link */}
        <Link
          href="/"
          className="group inline-flex items-center gap-2 text-xs uppercase tracking-widest text-muted-grey hover:text-primary-black mb-12 transition-colors"
        >
          <ArrowLeft className="w-3.5 h-3.5 group-hover:-translate-x-1 transition-transform" />
          Back to Home
        </Link>

        {/* Content Box */}
        <div className="max-w-[900px] mx-auto bg-white border border-border-grey p-8 md:p-16 rounded-2xl shadow-xs space-y-12">
          {/* Header */}
          <div className="border-b border-border-grey pb-6">
            <span className="text-[10px] uppercase tracking-widest font-bold text-primary-black flex items-center gap-1.5 mb-2">
              <ShieldCheck className="w-4 h-4" /> Legal Department
            </span>
            <h1 className="font-display text-3xl md:text-4xl font-light text-primary-black uppercase tracking-wider">
              Privacy Policy & Terms of Service
            </h1>
            <p className="text-[10px] uppercase tracking-widest text-muted-grey mt-1">
              Effective Date: June 2026 • Official Document ID: AN-PL-2026-V1
            </p>
          </div>

          <div className="space-y-8 text-xs md:text-sm text-dark-grey font-light leading-relaxed">
            
            {/* Introductory Notice */}
            <div className="bg-soft-bg p-6 border border-border-grey rounded-xl flex items-start gap-4">
              <Scale className="w-8 h-8 text-primary-black shrink-0 mt-0.5" />
              <div>
                <p className="text-xs font-semibold text-primary-black uppercase tracking-wider mb-1">
                  Professional Agreement
                </p>
                <p className="text-[11px] text-dark-grey">
                  This document governs the access and usage terms of this portfolio website. By visiting this site or submitting information, you agree to the terms specified herein. All interactions are treated with the utmost professional confidentiality.
                </p>
              </div>
            </div>

            {/* Section 1 */}
            <div className="space-y-3">
              <h3 className="font-display text-base uppercase tracking-wider text-primary-black font-semibold flex items-center gap-1.5 mt-8 border-b border-border-grey/50 pb-2">
                1. Data Privacy & Confidentiality
              </h3>
              <p>
                Any information submitted through contact forms, newsletters, or diagnostic calculators is securely stored and used strictly for the purpose of fulfilling your request, providing consultations, and sharing relevant insights. We never sell, rent, or distribute your personal data to third parties.
              </p>
              <p>
                Your privacy is of paramount importance, and industry-standard security measures are implemented to protect all correspondence and proprietary details you share.
              </p>
            </div>

            {/* Section 2 */}
            <div className="space-y-3">
              <h3 className="font-display text-base uppercase tracking-wider text-primary-black font-semibold flex items-center gap-1.5 mt-8 border-b border-border-grey/50 pb-2">
                2. Intellectual Property
              </h3>
              <p>
                The content, design, code, and case studies showcased on this portfolio are the intellectual property of Ankit Nishad, unless otherwise stated. Unauthorized reproduction, scraping, or commercial use of this website's assets without prior written consent is prohibited.
              </p>
            </div>

            {/* Section 3 */}
            <div className="space-y-3">
              <h3 className="font-display text-base uppercase tracking-wider text-primary-black font-semibold flex items-center gap-1.5 mt-8 border-b border-border-grey/50 pb-2">
                3. Disclaimer
              </h3>
              <p>
                The automated estimates generated by any calculators on this site are projections based on industry standards. They serve as a baseline for discussion and do not constitute formal binding financial advisories or guaranteed outcomes.
              </p>
            </div>

            {/* Sign-off & Official Seal stamp */}
            <div className="pt-12 border-t border-border-grey mt-12 flex flex-col md:flex-row justify-between items-center gap-8">
              <div className="space-y-2 text-center md:text-left">
                <p className="text-xs text-muted-grey">
                  For legal inquiries, terms compliance, or written requests, please contact:
                </p>
                <p className="font-semibold text-primary-black">
                  ankitnishad703@gmail.com
                </p>
                <p className="text-[10px] text-muted-grey uppercase tracking-widest font-semibold mt-4">
                  Authorized Signatory: Ankit Nishad
                </p>
              </div>

              {/* Official Stamp image */}
              <div className="shrink-0 relative">
                <img 
                  src="/assets/offical%20stamp.png" 
                  alt="Authorized Signature Stamp Seal" 
                  className="w-40 h-40 md:w-48 md:h-48 object-contain mix-blend-multiply opacity-90"
                />
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
  );
}
